version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "grixu"
      - "Mat3uszkek"
      - "grzywaczek"
    commit-message:
      prefix: ":arrow_up: chore: "
